server:
  port: 8090
  maxHttpHeaderSize: 8192

spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://sapi-interface:8123
          predicates:
            - Path=/api/**

